### ISSUE TITLE
ui.tags.head() not being hoisted into <head>

### ISSUE THREAD

**Issue by jcheng5** [wch/shinycomponent#14]
Instead, the <style> or whatever appears inside a custom tag, and they don't seem to work there.

Partial example:

```
sc.page_dashboard(
    ui.tags.head(
            ui.tags.style(
        """
        body > shiny-dashboard > shiny-tab:nth-child(1) > shiny-grid > shiny-card:nth-child(2) {
            --card-bg: red;
            border: 1px solid blue !important;
        }
        """
    ),
```

**Comment by wch** [comment]
I believe that in general, we doing hoist `tags.head()` stuff into the `<head>` of the document. That's what the `head_content()` function is for.

For example, see:

https://github.com/rstudio/py-shiny/blob/53e7755a2caef040e9e5961fab53b784511511af/shiny/experimental/ui/_page.py#L229-L293

https://github.com/rstudio/py-shiny/blob/53e7755a2caef040e9e5961fab53b784511511af/shiny/ui/_page.py#L203-L234

**Comment by jcheng5** [comment]
Oh, I didn't know that. So `page_fillable` should be using `head_content` too.

**Comment by jcheng5** [comment]
I snuck the fix to `page_fillable` into https://github.com/rstudio/py-shiny/pull/650

**Comment by wch** [comment]
Ugh, typo:

> we doing hoist

Should be:

> we don't hoist

But it sounds like you were able to figure out what I meant!
